const sheetNames = [
	"hca",
	"hca_bhs",
	"hca_chs",
	"hca_hca",
	"hca_mhs",
	"hca_occ",
	"hca_phs",
	"urgent_care",
	"long_term_care",
	"home_health_agencies",
	"dialysis_centers",
	"community_clinics",
	"veterans_health_administration",
	"hospitals",
];

const dictionary = [
	{
		id: "0b9dcad9-2dfe-48d1-8000-d06e8a33af73",
		overlay_type: "urgent_care",
		gemoetry_type: "point",
		title_key: "overlay_urgent_care",
		title: "Urgent Care Facilities",
		parent: "hospital_resources",
	},
	{
		id: "29b5d557-bbcc-49ee-a996-5dcf6cd2e811",
		overlay_type: "long_term_care",
		gemoetry_type: "point",
		title_key: "overlay_long_term_care",
		title: "Long Term Care Facilities",
		parent: "hospital_resources",
	},
	{
		id: "99f3071c-2d78-430c-b2ef-d32573d6f970",
		overlay_type: "home_health_agencies",
		gemoetry_type: "point",
		title_key: "overlay_home_health_agencies",
		title: "Home Health Agencies and Hospice",
		parent: "hospital_resources",
	},
	{
		id: "d2c3d694-c126-45fc-97e3-363ea4f4dea3",
		overlay_type: "dialysis_centers",
		gemoetry_type: "point",
		title_key: "overlay_dialysis_centers",
		title: "Dialysis Centers",
		parent: "hospital_resources",
	},
	{
		id: "859cf1bf-7b75-49b2-a34b-a8066d766f61",
		overlay_type: "community_clinics",
		gemoetry_type: "point",
		title_key: "overlay_community_clinics",
		title: "Community Clinics",
		parent: "hospital_resources",
	},
	{
		id: "04977d83-d21a-4256-9b9c-6908b37595b8",
		overlay_type: "veterans_health_administration",
		gemoetry_type: "point",
		title_key: "overlay_veterans_health_administration",
		title: "Veterans Health Administration",
		parent: "hospital_resources",
	},
	{
		id: "598ee556-7afe-4d19-8724-fa72762fc16e",
		overlay_type: "hospitals",
		gemoetry_type: "point",
		title_key: "overlay_hospitals",
		title: "Hospitals",
		parent: "hospital_resources",
	},
	{
		id: "e44e92c0-d038-41db-b404-01f1fad33c76",
		overlay_type: "hca",
		gemoetry_type: "point",
		title_key: "overlay_hca",
		title: "HCA Sites",
		parent: "hospital_resources",
	},
	{
		id: "89fe209f-8fa4-4ab3-b07b-a71b80ed0c3f",
		overlay_type: "hca_bhs",
		gemoetry_type: "point",
		title_key: "overlay_hca_bhs",
		title: "HCA Sites BHS",
		parent: "hospital_resources",
	},
	{
		id: "ea2620c7-fb90-47d8-85e1-b65e51a2fcf1",
		overlay_type: "hca_chs",
		gemoetry_type: "point",
		title_key: "overlay_hca_chs",
		title: "HCA Sites CHS",
		parent: "hospital_resources",
	},
	{
		id: "5960f44b-ad75-482a-befc-1ba15bd23f88",
		overlay_type: "hca_hca",
		gemoetry_type: "point",
		title_key: "overlay_hca_hca",
		title: "HCA Sites HCA",
		parent: "hospital_resources",
	},
	{
		id: "15e4b37d-27b1-43db-bda6-5cd1ffade701",
		overlay_type: "hca_mhs",
		gemoetry_type: "point",
		title_key: "overlay_hca_mhs",
		title: "HCA Sites MHS",
		parent: "hospital_resources",
	},
	{
		id: "9bd7416d-cb8d-442f-b395-4eaf833c21ac",
		overlay_type: "hca_occ",
		gemoetry_type: "point",
		title_key: "overlay_hca_occ",
		title: "HCA Sites OCC",
		parent: "hospital_resources",
	},
	{
		id: "c486ef3b-2e54-40db-a397-afca65aea0a7",
		overlay_type: "hca_phs",
		gemoetry_type: "point",
		title_key: "overlay_hca_phs",
		title: "HCA Sites PHS",
		parent: "hospital_resources",
	},
	{
		id: "f3554ae8-dfac-44dd-8d6a-9904b84878f3",
		overlay_type: "covid_cases_census",
		gemoetry_type: "range",
		title_key: "overlay_covid_cases_census",
		title: "",
		parent: "covid_cases",
	},
	{
		id: "d7a28bc2-7ac6-4bba-8da0-8cc58bd74867",
		overlay_type: "covid_cases_census_2021",
		gemoetry_type: "range",
		title_key: "overlay_covid_cases_census_2021",
		title: "",
		parent: "covid_cases",
	},
	{
		id: "4d0f7308-d752-4cc3-b809-3681caf8288f",
		overlay_type: "covid_cases_census_2022",
		gemoetry_type: "range",
		title_key: "overlay_covid_cases_census_2022",
		title: "",
		parent: "covid_cases",
	},
	{
		id: "502e9523-ab4a-414d-b805-dda279ff23da",
		overlay_type: "covid_cases_zip",
		gemoetry_type: "range",
		title_key: "overlay_covid_cases_zip",
		title: "",
		parent: "covid_cases",
	},
	{
		id: "58a4cc46-a8f1-4aa7-9fcd-a1d0c124fa02",
		overlay_type: "case_rate_city",
		gemoetry_type: "range",
		title_key: "overlay_case_rate_city",
		title: "",
		parent: "covid_rate_testing_city",
	},
	{
		id: "75c683e6-173f-4f03-af76-e66385a3ec2d",
		overlay_type: "positivity_percent_city",
		gemoetry_type: "range",
		title_key: "overlay_positivity_percent_city",
		title: "",
		parent: "covid_rate_testing_city",
	},
	{
		id: "4f181999-0d14-48af-85d7-42a424912920",
		overlay_type: "case_rate_cumulative_city",
		gemoetry_type: "range",
		title_key: "overlay_case_rate_cumulative_city",
		title: "",
		parent: "covid_rate_testing_city",
	},
	{
		id: "ee0814d1-fde6-4145-9ce2-20de201f7e08",
		overlay_type: "case_rate_zip",
		gemoetry_type: "range",
		title_key: "overlay_case_rate_zip",
		title: "",
		parent: "covid_rate_testing_zip",
	},
	{
		id: "64f2bc3a-bc17-484a-9130-ddcad1c6eaaa",
		overlay_type: "positivity_percent_zip",
		gemoetry_type: "range",
		title_key: "overlay_positivity_percent_zip",
		title: "",
		parent: "covid_rate_testing_zip",
	},
	{
		id: "09a31db9-0e61-4263-bf0e-81835435899d",
		overlay_type: "case_rate_cumulative_zip",
		gemoetry_type: "range",
		title_key: "overlay_case_rate_cumulative_zip",
		title: "",
		parent: "covid_rate_testing_zip",
	},
	{
		id: "7bb27421-cd9e-4e25-92e9-cf06af0c7579",
		overlay_type: "all",
		gemoetry_type: "point",
		title_key: "overlay_all",
		title: "",
		parent: "school_districts",
	},
	{
		id: "5dc6fc8d-1196-4417-bd83-398ace92d48b",
		overlay_type: "Brea-Olinda Unified",
		gemoetry_type: "point",
		title_key: "Brea-Olinda Unified",
		title: "",
		parent: "school_districts",
	},
	{
		id: "c8e50568-955a-46f7-a988-5092f3796b13",
		overlay_type: "Placentia-Yorba Linda Unified",
		gemoetry_type: "point",
		title_key: "Placentia-Yorba Linda Unified",
		title: "",
		parent: "school_districts",
	},
	{
		id: "7b1d2fb6-39ac-42f2-ba54-462606070e55",
		overlay_type: "Los Alamitos Unified",
		gemoetry_type: "point",
		title_key: "Los Alamitos Unified",
		title: "",
		parent: "school_districts",
	},
	{
		id: "e6c199ff-90d1-4c92-a2d2-0c84b90dc1db",
		overlay_type: "Garden Grove Unified",
		gemoetry_type: "point",
		title_key: "Garden Grove Unified",
		title: "",
		parent: "school_districts",
	},
	{
		id: "71f5f70a-86fa-4f03-8694-878cf384a559",
		overlay_type: "Santa Ana Unified",
		gemoetry_type: "point",
		title_key: "Santa Ana Unified",
		title: "",
		parent: "school_districts",
	},
	{
		id: "b6321707-ac3f-4c61-99b6-86f673791c3b",
		overlay_type: "Saddleback Valley Unified",
		gemoetry_type: "point",
		title_key: "Saddleback Valley Unified",
		title: "",
		parent: "school_districts",
	},
	{
		id: "2dbe055a-103a-425a-a10d-fdab304c69e3",
		overlay_type: "Laguna Beach Unified",
		gemoetry_type: "point",
		title_key: "Laguna Beach Unified",
		title: "",
		parent: "school_districts",
	},
	{
		id: "068d1cc7-2dee-4ed5-83f3-a5d34fee3e92",
		overlay_type: "Irvine Unified",
		gemoetry_type: "point",
		title_key: "Irvine Unified",
		title: "",
		parent: "school_districts",
	},
	{
		id: "8191e241-d670-4801-b61c-b019d429b9f7",
		overlay_type: "Newport-Mesa Unified",
		gemoetry_type: "point",
		title_key: "Newport-Mesa Unified",
		title: "",
		parent: "school_districts",
	},
	{
		id: "91d29330-b64e-4501-8112-b0d336d10e60",
		overlay_type: "Capistrano Unified",
		gemoetry_type: "point",
		title_key: "Capistrano Unified",
		title: "",
		parent: "school_districts",
	},
	{
		id: "8cda3cc6-c4b4-41cd-84e8-67cba4641b19",
		overlay_type: "Tustin Unified",
		gemoetry_type: "point",
		title_key: "Tustin Unified",
		title: "",
		parent: "school_districts",
	},
	{
		id: "ea5582c1-0629-463b-b752-b0b99aba3d23",
		overlay_type: "Orange Unified",
		gemoetry_type: "point",
		title_key: "Orange Unified",
		title: "",
		parent: "school_districts",
	},
	{
		id: "1bf6770c-cd8b-49a4-9423-984493d4dfd7",
		overlay_type: "Lowell Joint / Fullerton Joint Union High",
		gemoetry_type: "point",
		title_key: "Lowell Joint / Fullerton Joint Union High",
		title: "",
		parent: "school_districts",
	},
	{
		id: "b746ab52-20ee-4ebd-825d-940a93366bd1",
		overlay_type: "La Habra City/ Fullerton  Joint Union High",
		gemoetry_type: "point",
		title_key: "La Habra City/ Fullerton  Joint Union High",
		title: "",
		parent: "school_districts",
	},
	{
		id: "fdbdd258-ae20-4ff5-9123-d34e294407f0",
		overlay_type: "Fullerton/ Fullerton Joint Union High",
		gemoetry_type: "point",
		title_key: "Fullerton/ Fullerton Joint Union High",
		title: "",
		parent: "school_districts",
	},
	{
		id: "1c9d440d-f216-421e-bd1c-b3d6b362ebf7",
		overlay_type: "Buena Park/ Fullerton  Joint Union High",
		gemoetry_type: "point",
		title_key: "Buena Park/ Fullerton  Joint Union High",
		title: "",
		parent: "school_districts",
	},
	{
		id: "52410f36-146b-4de3-9020-3abe4e3c44f9",
		overlay_type: "Anaheim Elementary/ Anaheim Union High",
		gemoetry_type: "point",
		title_key: "Anaheim Elementary/ Anaheim Union High",
		title: "",
		parent: "school_districts",
	},
	{
		id: "b1e18a42-c8af-4cf6-9f89-ecc1da44bf2a",
		overlay_type: "Centralia Elementary/ Anaheim Union High",
		gemoetry_type: "point",
		title_key: "Centralia Elementary/ Anaheim Union High",
		title: "",
		parent: "school_districts",
	},
	{
		id: "709579a8-c018-4f38-a3ea-b05c5bb52715",
		overlay_type: "Cypress / Anahim Union High",
		gemoetry_type: "point",
		title_key: "Cypress / Anahim Union High",
		title: "",
		parent: "school_districts",
	},
	{
		id: "534f7743-c810-472b-85df-6736eb0783b3",
		overlay_type: "Magnolia/ Anaheim Union High",
		gemoetry_type: "point",
		title_key: "Magnolia/ Anaheim Union High",
		title: "",
		parent: "school_districts",
	},
	{
		id: "0ec1c24e-f8fd-4451-a180-5cba574f44f9",
		overlay_type: "Savanna/ Anaheim Union High",
		gemoetry_type: "point",
		title_key: "Savanna/ Anaheim Union High",
		title: "",
		parent: "school_districts",
	},
	{
		id: "c59de6e3-9934-481d-ac76-71159fc6757f",
		overlay_type: "Westminster/Huntington Beach Union High",
		gemoetry_type: "point",
		title_key: "Westminster/Huntington Beach Union High",
		title: "",
		parent: "school_districts",
	},
	{
		id: "0e9cfbeb-c6d6-4323-96dd-6e3a0b48fac5",
		overlay_type: "Ocean View/ Huntington Beach Union High",
		gemoetry_type: "point",
		title_key: "Ocean View/ Huntington Beach Union High",
		title: "",
		parent: "school_districts",
	},
	{
		id: "12068ade-f3f2-4197-838b-f430e4372be2",
		overlay_type: "Huntington Beach City/Huntington Beach Union High",
		gemoetry_type: "point",
		title_key: "Huntington Beach City/Huntington Beach Union High",
		title: "",
		parent: "school_districts",
	},
	{
		id: "925e52b9-0d6b-496f-8ac5-90aabdd40f23",
		overlay_type: "Fountain Valley/ Fullerton Joint Union High",
		gemoetry_type: "point",
		title_key: "Fountain Valley/ Fullerton Joint Union High",
		title: "",
		parent: "school_districts",
	},
];

module.exports = { sheetNames, dictionary };
