const requiredSheets = [
	"spi-values",
	"spi-rankings",
	"spi-scorecards",
	"spi-peer-groups",
	"cdc",
	"demographics",
];

const dictionary = [
	{
		id: "3a5cd880-679b-496d-b28e-807ad2dd51ba",
		layer_type: "spi",
		content_key: "aic_celldata",
		title_key: "baselayer_spi_aic_celldata",
		title: "Cellular Data Subscription (% of Population)",
		parent: "aic",
		level: 3,
	},
	{
		id: "91093eb0-77eb-4acf-bc78-ac28720d5b12",
		layer_type: "spi",
		content_key: "s_rapi",
		title_key: "baselayer_spi_s_rapi",
		title: "Rental Assistance Priority Index",
		parent: "housing",
		level: 3,
	},
	{
		id: "91093eb0-77eb-4acf-bc78-ac28720d5b13",
		layer_type: "spi",
		content_key: "ws_groundwater",
		title_key: "baselayer_spi_ws_groundwater",
		title: "Groundwater",
		parent: "ws",
		level: 3,
	},
	{
		id: "91093eb0-77eb-4acf-bc78-ac28720d5b11",
		layer_type: "spi",
		content_key: "eq",
		title_key: "baselayer_spi_eq",
		title: "Environmental Quality",
		parent: "wf",
		level: 2,
		is_category: true,
		selectable: true,
		is_open: false,
	},
	{
		id: "5c99d1cf-b93f-44c6-aa73-45931365d697",
		layer_type: "spi",
		content_key: "eq_no2",
		title_key: "baselayer_spi_eq_no2",
		title: "Traffic Density",
		parent: "eq",
		level: 3,
	},
	{
		id: "822ad40d-9d4f-4f27-965e-cc0fa37cb280",
		layer_type: "spi",
		content_key: "eq_pm25",
		title_key: "baselayer_spi_eq_pm25",
		title: "PM2.5 Average Annual Concentration (μg/m3)",
		parent: "eq",
		level: 3,
	},
	{
		id: "61a715d9-15fd-43cf-8441-80a2f0b172b5",
		layer_type: "spi",
		content_key: "eq_ozone",
		title_key: "baselayer_spi_eq_ozone",
		title: "Ozone Average 8-hour Concentration (ppm)",
		parent: "eq",
		level: 3,
	},
	{
		id: "6ab80045-ef3a-43c9-8a2b-cb627ae93fc8",
		layer_type: "spi",
		content_key: "eq_wildfirehp",
		title_key: "baselayer_spi_eq_wildfirehp",
		title: "Wildfire Hazard Potential",
		parent: "eq",
		level: 3,
	},
	{
		id: "b70fd9e0-a76b-46e9-b102-70286d00d87a",
		layer_type: "spi",
		content_key: "eq_carbonfootprint",
		title_key: "baselayer_spi_eq_carbonfootprint",
		title: "Carbon Footprint (Metric Tons CO2)",
		parent: "eq",
		level: 3,
	},
	{
		id: "69df24cd-f3f8-4e0f-8adf-a6bbe938fddd",
		layer_type: "spi",
		content_key: "hw",
		title_key: "baselayer_spi_hw",
		title: "Health and Wellness",
		parent: "wf",
		level: 2,
		is_category: true,
		selectable: true,
		is_open: false,
	},
	{
		id: "56172bfb-5baf-408c-8d90-af670fb3bdbb",
		layer_type: "spi",
		content_key: "hw_cancer",
		title_key: "baselayer_spi_hw_cancer",
		title: "Cancer Prevalence (% of Adults)",
		parent: "hw",
		level: 3,
	},
	{
		id: "07ab6c8d-4aa8-4315-94ec-fae70e3d07b5",
		layer_type: "spi",
		content_key: "hw_obesity",
		title_key: "baselayer_spi_hw_obesity",
		title: "Obesity Prevalence (% of Adults)",
		parent: "hw",
		level: 3,
	},
	{
		id: "31e611b5-8e28-40f4-82e5-1b460c83c295",
		layer_type: "spi",
		content_key: "hw_diabetes",
		title_key: "baselayer_spi_hw_diabetes",
		title: "Diabetes Prevalence (% of Adults)",
		parent: "hw",
		level: 3,
	},
	{
		id: "ea1218b4-22ec-4a3a-a09b-2a065f3f67ff",
		layer_type: "spi",
		content_key: "hw_mentalhealth",
		title_key: "baselayer_spi_hw_mentalhealth",
		title: "Poor Mental Health Days",
		parent: "hw",
		level: 3,
	},
	{
		id: "551d7278-0068-47e1-a0a9-c9134f40c9a7",
		layer_type: "spi",
		content_key: "hw_under5_physicalhealth",
		title_key: "baselayer_spi_hw_under5_physicalhealth",
		title: "Vulnerable or at Risk in Physical Health (% of Children Under 5)",
		parent: "hw",
		level: 3,
	},
	{
		id: "d0f60527-e056-48dc-89ca-b002b6758b18",
		layer_type: "spi",
		content_key: "abk",
		title_key: "baselayer_spi_abk",
		title: "Access to Basic Knowledge",
		parent: "wf",
		level: 2,
		is_category: true,
		selectable: true,
		is_open: false,
	},
	{
		id: "d5dbcf5b-6b5c-420a-9d62-9c9fc36ee339",
		layer_type: "spi",
		content_key: "abk_g8math",
		title_key: "baselayer_spi_abk_g8math",
		title: "Eighth Grade Math Proficiency (% of 8th Graders)",
		parent: "abk",
		level: 3,
	},
	{
		id: "880a2b55-0b19-4c47-a08b-21d202c657e6",
		layer_type: "spi",
		content_key: "abk_g3reading",
		title_key: "baselayer_spi_abk_g3reading",
		title: "Third Grade Language Arts Proficiency (% of 3rd Graders)",
		parent: "abk",
		level: 3,
	},
	{
		id: "38b7ac6a-eb40-49ce-89da-941efaa0e24a",
		layer_type: "spi",
		content_key: "abk_hsincomplete",
		title_key: "baselayer_spi_abk_hsincomplete",
		title: "Population Without a High School Diploma or Equivalent (% of 18-24 Year Olds)",
		parent: "abk",
		level: 3,
	},
	{
		id: "b98145cb-72ee-493e-9b96-63d6285c45c9",
		layer_type: "spi",
		content_key: "abk_under5_comskills",
		title_key: "baselayer_spi_abk_under5_comskills",
		title: "Communication and General Knowledge (% of Children Under 5)",
		parent: "abk",
		level: 3,
	},
	{
		id: "8616b617-d575-4842-894c-9b73b09a1e5c",
		layer_type: "spi",
		content_key: "abk_under5_socioemotional",
		title_key: "baselayer_spi_abk_under5_socioemotional",
		title: "Social-Emotional Vulnerable (% of Children Under 5)",
		parent: "abk",
		level: 3,
	},
	{
		id: "a258a515-b2e1-4cce-95c3-a57dad92102d",
		layer_type: "spi",
		content_key: "aic",
		title_key: "baselayer_spi_aic",
		title: "Access to Information and Communications",
		parent: "wf",
		level: 2,
		is_category: true,
		selectable: true,
		is_open: false,
	},
	{
		id: "421b78f5-f89b-44d6-888d-56396b989697",
		layer_type: "spi",
		content_key: "wf",
		title_key: "baselayer_spi_wf",
		title: "Foundations of Wellbeing",
		parent: "spi",
		level: 1,
		is_category: true,
		selectable: true,
		is_open: false,
	},
	{
		id: "48e280bb-b45e-49a2-82fd-7b07a4b41bd7",
		layer_type: "spi",
		content_key: "aic_broadband",
		title_key: "baselayer_spi_aic_broadband",
		title: "Broadband subscriptions (% of population)",
		parent: "aic",
		level: 3,
	},
	{
		id: "7f95f62e-6d4a-4e53-821f-0eab8a089044",
		layer_type: "spi",
		content_key: "aic_nointernet",
		title_key: "baselayer_spi_aic_nointernet",
		title: "No internet access (% of population)",
		parent: "aic",
		level: 3,
	},
	{
		id: "2f3f61f9-cd6e-4452-8f2e-1b89a2a0110a",
		layer_type: "spi",
		content_key: "aic_hascomputer",
		title_key: "baselayer_spi_aic_hascomputer",
		title: "One or More Types of Computing Devices Present (% of Households)",
		parent: "aic",
		level: 3,
	},
	{
		id: "48412303-72b2-4113-a2d3-678e8331d771",
		layer_type: "spi",
		content_key: "aic_broadbandspeed",
		title_key: "baselayer_spi_aic_broadbandspeed",
		title: "Average broadband speed (Mbps download)",
		parent: "aic",
		level: 3,
	},
	{
		id: "589445df-394c-47c6-8aea-1041f1f149e6",
		layer_type: "spi",
		content_key: "bhn",
		title_key: "baselayer_spi_bhn",
		title: "Basic Human Needs",
		parent: "spi",
		level: 1,
		is_category: true,
		selectable: true,
		is_open: false,
	},
	{
		id: "661098a6-4f81-4757-a52c-33b1f9e727dc",
		layer_type: "spi",
		content_key: "ps",
		title_key: "baselayer_spi_ps",
		title: "Personal Safety",
		parent: "bhn",
		level: 2,
		is_category: true,
		selectable: true,
		is_open: false,
	},
	{
		id: "951ceac9-cd4a-477f-bcf2-fa7421a05235",
		layer_type: "spi",
		content_key: "ps_violent",
		title_key: "baselayer_spi_ps_violent",
		title: "Violent crime rate (per 10,000 population)",
		parent: "ps",
		level: 3,
	},
	{
		id: "c0f347fa-cf6b-4d1f-a7d5-4c3d8593325b",
		layer_type: "spi",
		content_key: "ps_property",
		title_key: "baselayer_spi_ps_property",
		title: "Property crime rate (per 10,000 population)",
		parent: "ps",
		level: 3,
	},
	{
		id: "2ab66f3f-5ff4-4fb0-813e-d703acba698e",
		layer_type: "spi",
		content_key: "ps_accidents",
		title_key: "baselayer_spi_ps_accidents",
		title: "Motor vehicle accident rate (per 10,000 population)",
		parent: "ps",
		level: 3,
	},
	{
		id: "d2a776b4-972c-48ac-94ab-f3706d59baa0",
		layer_type: "spi",
		content_key: "ws",
		title_key: "baselayer_spi_ws",
		title: "Water and Sanitation",
		parent: "bhn",
		level: 2,
		is_category: true,
		selectable: true,
		is_open: false,
	},
	{
		id: "bdcd0ed8-7324-410f-802d-250b059dfe68",
		layer_type: "spi",
		content_key: "ws_inspections",
		title_key: "baselayer_spi_ws_inspections",
		title: "Businesses in Compliance With Health Standards (% Total Businesses Inspected)",
		parent: "ws",
		level: 3,
	},
	// {
	// 	id: "d92a4d21-c6e0-4006-8ffd-8bf116353f41",
	// 	layer_type: "spi",
	// 	content_key: "ws_drinkingwater",
	// 	title_key: "baselayer_spi_ws_drinkingwater",
	// 	title: "Safe Drinking Water Act Health-based Violations",
	// 	parent: "ws",
	// 	level: 3,
	// },
	{
		id: "236f4efd-aa16-47da-a75d-97652d63fd8d",
		layer_type: "spi",
		content_key: "ws_hazardouswaste",
		title_key: "baselayer_spi_ws_hazardouswaste",
		title: "Hazardous Waste",
		parent: "ws",
		level: 3,
	},
	{
		id: "dbb44686-d2e9-4cdb-bc56-b894cba594eb",
		layer_type: "spi",
		content_key: "nbm",
		title_key: "baselayer_spi_nbm",
		title: "Nutrition and Basic Medical Care",
		parent: "bhn",
		level: 2,
		is_category: true,
		selectable: true,
		is_open: false,
	},
	{
		id: "78c44931-6893-4f88-9386-91a8662824e6",
		layer_type: "spi",
		content_key: "nbm_vax",
		title_key: "baselayer_spi_nbm_vax",
		title: "Kindergarten Vaccination Rate (% of Kindergarteners)",
		parent: "nbm",
		level: 3,
	},
	{
		id: "62222943-7175-4c11-9ca2-b607c4cca86a",
		layer_type: "spi",
		content_key: "nbm_dental",
		title_key: "baselayer_spi_nbm_dental",
		title: "Dental Care Visits (% of Adults)",
		parent: "nbm",
		level: 3,
	},
	{
		id: "6ad28b1b-18d4-48ae-8227-2cbfef49d657",
		layer_type: "spi",
		content_key: "nbm_foodstamps",
		title_key: "baselayer_spi_nbm_foodstamps",
		title: "Households With Food Stamp Benefits in the Past 12 months (% of Households)",
		parent: "nbm",
		level: 3,
	},
	{
		id: "d9bbdfa6-054a-48c8-be16-942c40ea6d94",
		layer_type: "spi",
		content_key: "nbm_preventative",
		title_key: "baselayer_spi_nbm_preventative",
		title: "Preventative Care Visits (% of Adults)",
		parent: "nbm",
		level: 3,
	},
	{
		id: "3b0804dc-7c7a-4e03-83d6-ccf5ffed658e",
		layer_type: "spi",
		content_key: "nbm_supermarketaccess",
		title_key: "baselayer_spi_nbm_supermarketaccess",
		title: "Supermarket Access (% of Population)",
		parent: "nbm",
		level: 3,
	},
	{
		id: "ee4ef2c0-10de-4d60-8b79-23b760c2c1e6",
		layer_type: "spi",
		content_key: "housing",
		title_key: "baselayer_spi_housing",
		title: "Housing",
		parent: "bhn",
		level: 2,
		is_category: true,
		selectable: true,
		is_open: false,
	},
	// {
	// 	id: "fc3df49e-861a-4b48-a3d9-828dfcbbdacc",
	// 	layer_type: "spi",
	// 	content_key: "s_eviction",
	// 	title_key: "baselayer_spi_s_eviction",
	// 	title: "Eviction Rate (per 100 renter homes)",
	// 	parent: "housing",
	// 	level: 3,
	// },
	{
		id: "20dfc601-89d3-4fa0-b7ce-81d524ecda00",
		layer_type: "spi",
		content_key: "s_overcrowded",
		title_key: "baselayer_spi_s_overcrowded",
		title: "Housing Overcrowding (% of Households)",
		parent: "housing",
		level: 3,
	},
	{
		id: "d3bf8449-fa3e-4eec-ad3d-31bffe718469",
		layer_type: "spi",
		content_key: "s_hburdenowner",
		title_key: "baselayer_spi_s_hburdenowner",
		title: "Housing Cost Burden (% of Households, Owners)",
		parent: "housing",
		level: 3,
	},
	{
		id: "582a44b1-d221-4ad9-8003-e9d1e7640b1e",
		layer_type: "spi",
		content_key: "s_hburdenrenter",
		title_key: "baselayer_spi_s_hburdenrenter",
		title: "Housing Cost Burden (% of Households, Renters)",
		parent: "housing",
		level: 3,
	},
	{
		id: "f6e09788-f2a4-4708-9f90-4b6e91398fee",
		layer_type: "spi",
		content_key: "mhi",
		title_key: "baselayer_spi_mhi",
		title: "Median Household Income",
		parent: "",
		level: 0,
	},
	{
		id: "2307a418-c505-4d11-aaa5-14a1b7dc31cb",
		layer_type: "spi",
		content_key: "spi",
		title_key: "baselayer_spi_spi",
		title: "Social Progress Index",
		parent: "",
		level: 0,
		is_category: true,
		selectable: true,
		is_open: false,
	},
	{
		id: "0bd9bf42-16af-4ff0-9614-f8755420316b",
		layer_type: "spi",
		content_key: "opportunity",
		title_key: "baselayer_spi_opportunity",
		title: "Oppotunity",
		parent: "spi",
		level: 1,
		is_category: true,
		selectable: true,
		is_open: false,
	},
	{
		id: "e01d1bd0-b9b1-4eb0-939e-1d0abc66a930",
		layer_type: "spi",
		content_key: "pr",
		title_key: "baselayer_spi_pr",
		title: "Personal Rights",
		parent: "opportunity",
		level: 2,
		is_category: true,
		selectable: true,
		is_open: false,
	},
	{
		id: "014ee8a3-3bf8-475d-b849-97e1327650ad",
		layer_type: "spi",
		content_key: "pr_turnout",
		title_key: "baselayer_spi_pr_turnout",
		title: "Voter Turnout (% of Voting Eligible Population)",
		parent: "pr",
		level: 3,
	},
	{
		id: "73287af8-c154-4a86-be3e-fca13b4ece52",
		layer_type: "spi",
		content_key: "pr_registration",
		title_key: "baselayer_spi_pr_registration",
		title: "Voter Registration Rate (% of Voting Eligible Population)",
		parent: "pr",
		level: 3,
	},
	{
		id: "7320198b-e9cc-4284-9cf0-31414dce5b21",
		layer_type: "spi",
		content_key: "pr_homeownership",
		title_key: "baselayer_spi_pr_homeownership",
		title: "Home Ownership (% of Households)",
		parent: "pr",
		level: 3,
	},
	{
		id: "d92b0653-6fc9-440f-87fb-a03ac5769988",
		layer_type: "spi",
		content_key: "aae",
		title_key: "baselayer_spi_aae",
		title: "Access to Advanced Education",
		parent: "opportunity",
		level: 2,
		is_category: true,
		selectable: true,
		is_open: false,
	},
	{
		id: "9bd886f4-2c6f-455e-bc8b-099de3836b15",
		layer_type: "spi",
		content_key: "aae_graduate",
		title_key: "baselayer_spi_aae_graduate",
		title: "Advanced Degree Holders (% of Population Age 25+)",
		parent: "aae",
		level: 3,
	},
	{
		id: "cd1d663b-c082-456e-8dec-ffff27265502",
		layer_type: "spi",
		content_key: "aae_bachelors",
		title_key: "baselayer_spi_aae_bachelors",
		title: "Bachelors Degree Holders (% of Population Age 25+)",
		parent: "aae",
		level: 3,
	},
	{
		id: "1cd860eb-481f-436b-abbd-3ced4611b05f",
		layer_type: "spi",
		content_key: "aae_associates",
		title_key: "baselayer_spi_aae_associates",
		title: "Associates Degree Holders (% of Population Age 25+)",
		parent: "aae",
		level: 3,
	},
	{
		id: "5db3b033-f38c-4258-b13f-7b15f7dd527a",
		layer_type: "spi",
		content_key: "pfc",
		title_key: "baselayer_spi_pfc",
		title: "Personal Freedom and Choice",
		parent: "opportunity",
		level: 2,
		is_category: true,
		selectable: true,
		is_open: false,
	},
	{
		id: "5431b778-d5a2-4f76-9ae2-13eae35a7188",
		layer_type: "spi",
		content_key: "pfc_walkindex",
		title_key: "baselayer_spi_pfc_walkindex",
		title: "Walkability Index",
		parent: "pfc",
		level: 3,
	},
	{
		id: "44246ade-7960-4f2c-90d0-195f52c29310",
		layer_type: "spi",
		content_key: "pfc_cleancommute",
		title_key: "baselayer_spi_pfc_cleancommute",
		title: "Alternative Transportation Usage (% of Commuters)",
		parent: "pfc",
		level: 3,
	},
	{
		id: "31c09e6c-3844-4977-a401-774505d6d656",
		layer_type: "spi",
		content_key: "pfc_disconnected",
		title_key: "baselayer_spi_pfc_disconnected",
		title: "Disconnected Youth (% of 16-19 Year Olds)",
		parent: "pfc",
		level: 3,
	},
	{
		id: "5f7955e8-cbc5-4ef4-8927-be1ac6968355",
		layer_type: "spi",
		content_key: "pfc_childcaredeserts",
		title_key: "baselayer_spi_pfc_childcaredeserts",
		title: "Child Care Deserts",
		parent: "pfc",
		level: 3,
	},
	{
		id: "e04ca610-60ea-4438-a832-82348a2a4564",
		layer_type: "spi",
		content_key: "inclusiveness",
		title_key: "baselayer_spi_inclusiveness",
		title: "Inclusiveness",
		parent: "opportunity",
		level: 2,
		is_category: true,
		selectable: true,
		is_open: false,
	},
	{
		id: "fcd2a1be-7ee4-4bae-8bcb-de47f418b5d8",
		layer_type: "spi",
		content_key: "i_isolation",
		title_key: "baselayer_spi_i_isolation",
		title: "Residential Isolation (Black/white)",
		parent: "inclusiveness",
		level: 3,
	},
	{
		id: "6e7600ab-b9f6-4443-bdf5-a7c9b8230102",
		layer_type: "spi",
		content_key: "i_linguistic",
		title_key: "baselayer_spi_i_linguistic",
		title: "Linguistic Isolation (% of Households)",
		parent: "inclusiveness",
		level: 3,
	},
	{
		id: "6e5a17ad-4716-4bb2-98e4-2120743e07c1",
		layer_type: "spi",
		content_key: "i_genderpaygap",
		title_key: "baselayer_spi_i_genderpaygap",
		title: "Gender Pay Gap",
		parent: "inclusiveness",
		level: 3,
	},
	{
		id: "9e204ef8-1410-4b0a-bcb5-bb86fc8698d5",
		layer_type: "spi",
		content_key: "i_dissimilarity",
		title_key: "baselayer_spi_i_dissimilarity",
		title: "Residential Segregation (Black/white)",
		parent: "inclusiveness",
		level: 3,
	},
	{
		id: "e41cfb6d-1d8b-43ee-b1c1-039d4e087176",
		layer_type: "cdc",
		content_key: "totalpopulation",
		title_key: "baselayer_cdc_totalpopulation",
		title: "Total Population",
		parent: "health_outcomes",
	},
	{
		id: "79040b00-6ab8-41ff-99c7-744c254ccd55",
		layer_type: "spi",
		content_key: "abk_preschoolenroll",
		title_key: "baselayer_spi_abk_preschoolenroll",
		title: "Preschool Enrollment (% of 3 and 4 Year Olds)",
		parent: "abk",
		level: 3,
	},
	{
		id: "f5909aa7-639e-4a47-aaa4-c64362239fe0",
		layer_type: "demographics",
		content_key: "totpop",
		title_key: "baselayer_demographics_totpop",
		title: "Total Population",
		parent: "general",
	},
	{
		id: "56e97fe7-b3b2-4a77-8895-4a4b3598f23c",
		layer_type: "cdc",
		content_key: "stroke_crudeprev",
		title_key: "baselayer_cdc_stroke_crudeprev",
		title: "Stroke Prevalence",
		parent: "health_outcomes",
	},
	{
		id: "9c0a4448-b40d-4aa5-8b83-ca799956005f",
		layer_type: "cdc",
		content_key: "diabetes_crudeprev",
		title_key: "baselayer_cdc_diabetes_crudeprev",
		title: "Diabetes Prevalence",
		parent: "health_outcomes",
	},
	{
		id: "f405e1de-54c7-4fd5-87c3-056c18daa26a",
		layer_type: "demographics",
		content_key: "medianhhinc",
		title_key: "baselayer_demographics_medianhhinc",
		title: "Median Household Income",
		parent: "general",
	},
	{
		id: "9e58d528-8617-4001-a707-c277c5c63a4e",
		layer_type: "demographics",
		content_key: "foreignborn",
		title_key: "baselayer_demographics_foreignborn",
		title: "% Foreign Born",
		parent: "general",
	},
	{
		id: "ab163ad2-0683-4111-9791-554d8d80245e",
		layer_type: "cdc",
		content_key: "bphigh_crudeprev",
		title_key: "baselayer_cdc_bphigh_crudeprev",
		title: "High Blood Pressure Prevalence",
		parent: "health_outcomes",
	},
	{
		id: "3a1c1dd7-05c0-46ad-ba77-bcaaec5e2d5c",
		layer_type: "cdc",
		content_key: "phlth_crudeprev",
		title_key: "baselayer_cdc_phlth_crudeprev",
		title: "Poor Physical Health 14+ Days",
		parent: "health_outcomes",
	},
	{
		id: "088e4031-929e-4f83-a3e7-3bc374f8839c",
		layer_type: "demographics",
		content_key: "poor",
		title_key: "baselayer_demographics_poor",
		title: "Poverty Rate",
		parent: "general",
	},
	{
		id: "4fc130e4-085d-4f12-b0f8-ea43ac4aa4a2",
		layer_type: "cdc",
		content_key: "cancer_crudeprev",
		title_key: "baselayer_cdc_cancer_crudeprev",
		title: "Cancer Prevalence (Except Skin)",
		parent: "health_outcomes",
	},
	{
		id: "9c87e4a4-f4c1-476f-a650-870a689ccafc",
		layer_type: "demographics",
		content_key: "below200pov",
		title_key: "baselayer_demographics_below200pov",
		title: "Below 200% Poverty Rate",
		parent: "general",
	},
	{
		id: "68622048-7f2d-4c47-b5e0-888fc9dbd711",
		layer_type: "cdc",
		content_key: "chd_crudeprev",
		title_key: "baselayer_cdc_chd_crudeprev",
		title: "Coronary Heart Disease",
		parent: "health_outcomes",
	},
	{
		id: "b23d1844-ec52-4c46-a914-6d802d765599",
		layer_type: "demographics",
		content_key: "disability",
		title_key: "baselayer_demographics_disability",
		title: "% with Disabilities",
		parent: "general",
	},
	{
		id: "3bcfce09-e441-43ee-9b4e-fef5fb2dc6ba",
		layer_type: "cdc",
		content_key: "casthma_crudeprev",
		title_key: "baselayer_cdc_casthma_crudeprev",
		title: "Asthma Prevalence",
		parent: "health_outcomes",
	},
	{
		id: "d537e286-89e0-4172-ad01-c1896c1e27f2",
		layer_type: "demographics",
		content_key: "white",
		title_key: "baselayer_demographics_white",
		title: "% White Population",
		parent: "ethnicity",
	},
	{
		id: "36d8d307-4c9a-49e4-a757-fe8728208a48",
		layer_type: "cdc",
		content_key: "checkup_crudeprev",
		title_key: "baselayer_cdc_checkup_crudeprev",
		title: "Regular Health Visits",
		parent: "health_outcomes",
	},
	{
		id: "2c6001e5-c09d-408d-83f2-a30085e94359",
		layer_type: "demographics",
		content_key: "black",
		title_key: "baselayer_demographics_black",
		title: "% Black Population",
		parent: "ethnicity",
	},
	{
		id: "45a61ad2-cecd-461a-97d9-0242ea4b3cb2",
		layer_type: "cdc",
		content_key: "corem_crudeprev",
		title_key: "baselayer_cdc_corem_crudeprev",
		title: "Male 65+ Regular Health Visits",
		parent: "prevention",
	},
	{
		id: "1a7878a1-cbe3-473a-88b7-d67141b060d8",
		layer_type: "demographics",
		content_key: "asian",
		title_key: "baselayer_demographics_asian",
		title: "% Asian Population",
		parent: "ethnicity",
	},
	{
		id: "9bd59cde-42bb-41e3-b69a-f7050103c7d9",
		layer_type: "demographics",
		content_key: "hispanicpop",
		title_key: "baselayer_demographics_hispanicpop",
		title: "% Hispanic Population",
		parent: "ethnicity",
	},
	{
		id: "d1145714-ae41-4b1c-b049-965a5dfa5a86",
		layer_type: "cdc",
		content_key: "corew_crudeprev",
		title_key: "baselayer_cdc_corew_crudeprev",
		title: "Female 65+ Regular Health Visits",
		parent: "prevention",
	},
	{
		id: "64950cbd-2d2e-41a1-876c-cb8ecfac76ff",
		layer_type: "cdc",
		content_key: "dental_crudeprev",
		title_key: "baselayer_cdc_dental_crudeprev",
		title: "Regular Dental Visits",
		parent: "health_outcomes",
	},
	{
		id: "33f049f5-6c77-490d-8b60-6df2cef38214",
		layer_type: "demographics",
		content_key: "multirace",
		title_key: "baselayer_demographics_multirace",
		title: "% Multirace Population",
		parent: "ethnicity",
	},
	{
		id: "b06572cf-e131-4ab1-96ba-d6f310e6bc52",
		layer_type: "demographics",
		content_key: "hawnpi",
		title_key: "baselayer_demographics_hawnpi",
		title: "% Hawaiian/Pacific Islander",
		parent: "ethnicity",
	},
	{
		id: "0cfd61db-67ef-4e31-86fc-ea024e0212c9",
		layer_type: "cdc",
		content_key: "mhlth_crudeprev",
		title_key: "baselayer_cdc_mhlth_crudeprev",
		title: "Poor Mental Health 14+ Days",
		parent: "health_outcomes",
	},
	{
		id: "df5c36a6-29b2-4844-8482-8efe54b121b3",
		layer_type: "cdc",
		content_key: "highchol_crudeprev",
		title_key: "baselayer_cdc_highchol_crudeprev",
		title: "High Cholesterol Past 5 Years",
		parent: "health_outcomes",
	},
	{
		id: "e3bb5acf-57d5-4ac5-aca1-2f932c4c97a4",
		layer_type: "demographics",
		content_key: "indian",
		title_key: "baselayer_demographics_indian",
		title: "% American Indian/Alaskan Native",
		parent: "ethnicity",
	},
	{
		id: "d283d710-8181-4dec-a530-89139e41b35c",
		layer_type: "demographics",
		content_key: "under5",
		title_key: "baselayer_demographics_under5",
		title: "Age Under 5",
		parent: "age_group",
	},
	{
		id: "649579f6-da37-40b4-afb9-96c021f7d3f0",
		layer_type: "cdc",
		content_key: "copd_crudeprev",
		title_key: "baselayer_cdc_copd_crudeprev",
		title: "COPD Prevalence",
		parent: "health_outcomes",
	},
	{
		id: "1613d7e3-2175-42fe-a903-469ca4293236",
		layer_type: "cdc",
		content_key: "kidney_crudeprev",
		title_key: "baselayer_cdc_kidney_crudeprev",
		title: "Chronic Kidney Disease Prevalence",
		parent: "health_outcomes",
	},
	{
		id: "8f303ba5-698d-4722-8905-9d52444a17ac",
		layer_type: "demographics",
		content_key: "age5_19",
		title_key: "baselayer_demographics_age5_19",
		title: "Age 5-19",
		parent: "age_group",
	},
	{
		id: "0d98a726-5618-42dc-8396-3870347ce83a",
		layer_type: "cdc",
		content_key: "arthritis_crudeprev",
		title_key: "baselayer_cdc_arthritis_crudeprev",
		title: "Arthritis Prevalence",
		parent: "health_outcomes",
	},
	{
		id: "0f56a1f7-fdc9-4a8b-8442-c49958ff90d7",
		layer_type: "demographics",
		content_key: "age20_34",
		title_key: "baselayer_demographics_age20_34",
		title: "Age 20-34",
		parent: "age_group",
	},
	{
		id: "21b2f74a-bf81-4325-81ff-9ba357a6f0a6",
		layer_type: "demographics",
		content_key: "age35_49",
		title_key: "baselayer_demographics_age35_49",
		title: "Age 35-49",
		parent: "age_group",
	},
	{
		id: "47dc94e8-f3e2-451f-8f91-f4c7f643d77b",
		layer_type: "cdc",
		content_key: "teethlost_crudeprev",
		title_key: "baselayer_cdc_teethlost_crudeprev",
		title: "All Teeth Lost 65+",
		parent: "health_outcomes",
	},
	{
		id: "c4634961-1436-488f-b923-fe0001c42ff5",
		layer_type: "cdc",
		content_key: "life_expectancy",
		title_key: "baselayer_cdc_life_expectancy",
		title: "Life Expectancy",
		parent: "health_outcomes",
	},
	{
		id: "a74b9262-f322-4a17-a1a1-12d4c7358039",
		layer_type: "demographics",
		content_key: "age50_65",
		title_key: "baselayer_demographics_age50_65",
		title: "Age 50-65",
		parent: "age_group",
	},
	{
		id: "0c71f274-9555-4e8b-b9df-5f41cbd6f2b5",
		layer_type: "cdc",
		content_key: "cervical_crudeprev",
		title_key: "baselayer_cdc_cervical_crudeprev",
		title: "Cervical Cancer Screen Women 21-65",
		parent: "prevention",
	},
	{
		id: "dccdcd08-058a-4768-be3b-bcf9fba6bb58",
		layer_type: "demographics",
		content_key: "over65",
		title_key: "baselayer_demographics_over65",
		title: "Age Over 65",
		parent: "age_group",
	},
	{
		id: "5172cd36-5c0d-4ff4-9615-5da160df249b",
		layer_type: "cdc",
		content_key: "cholscreen_crudeprev",
		title_key: "baselayer_cdc_cholscreen_crudeprev",
		title: "Cholesterol Screening Prevalence",
		parent: "prevention",
	},
	{
		id: "a4f4da36-74a4-44f2-8994-e341596bea3d",
		layer_type: "cdc",
		content_key: "colon_screen_crudeprev",
		title_key: "baselayer_cdc_colon_screen_crudeprev",
		title: "Fecal Occult Blood Test, Sigmoidoscopy, Colonoscopy in 50-75",
		parent: "prevention",
	},
	{
		id: "cfe417ef-fad5-4fb7-90c4-a8853e50570a",
		layer_type: "cdc",
		content_key: "access2_crudeprev",
		title_key: "baselayer_cdc_access2_crudeprev",
		title: "Percent Uninsured Adults",
		parent: "prevention",
	},
	{
		id: "f7954d5c-c45d-49cf-9e29-a5e849b8e644",
		layer_type: "cdc",
		content_key: "bpmed_crudeprev",
		title_key: "baselayer_cdc_bpmed_crudeprev",
		title: "% Taking High Blood Pressure Medication",
		parent: "prevention",
	},
	{
		id: "39bac2ef-84c9-4ae9-b1d2-67152d7e62d0",
		layer_type: "cdc",
		content_key: "mammouse_crudeprev",
		title_key: "baselayer_cdc_mammouse_crudeprev",
		title: "Mammography Usage 50-74 Years",
		parent: "prevention",
	},
	{
		id: "90644b9f-0905-4a7a-b5d1-6ca964718d7a",
		layer_type: "cdc",
		content_key: "sleep_crudeprev",
		title_key: "baselayer_cdc_sleep_crudeprev",
		title: "Less Than 7 Hours Sleep in Adults",
		parent: "unhealthy_behaviors",
	},
	{
		id: "ee7ba7a3-b8dd-4807-8e90-20d05655ceb1",
		layer_type: "cdc",
		content_key: "binge_crudeprev",
		title_key: "baselayer_cdc_binge_crudeprev",
		title: "Adult Binge Drinking Prevalence",
		parent: "unhealthy_behaviors",
	},
	{
		id: "f8cd917b-97d6-457f-a27d-2848576dcd7b",
		layer_type: "cdc",
		content_key: "obesity_crudeprev",
		title_key: "baselayer_cdc_obesity_crudeprev",
		title: "Obesity Prevalence",
		parent: "unhealthy_behaviors",
	},
	{
		id: "86e5be9e-efed-4e90-b3a7-040aa950074d",
		layer_type: "cdc",
		content_key: "lpa_crudeprev",
		title_key: "baselayer_cdc_lpa_crudeprev",
		title: "No Leisure Physical Activity",
		parent: "unhealthy_behaviors",
	},
	{
		id: "6430036a-4562-478a-bf1a-420f669952b1",
		layer_type: "cdc",
		content_key: "csmoking_crudeprev",
		title_key: "baselayer_cdc_csmoking_crudeprev",
		title: "Smoking Prevalence in Adults",
		parent: "unhealthy_behaviors",
	},
	{
		id: "650469fa-c728-4753-950e-966062360468",
		layer_type: "cdc",
		content_key: "depression_crudeprev",
		title_key: "baselayer_cdc_depression_crudeprev",
		title: "Depression Among Adults 18+",
		parent: "health_outcomes",
	},
	{
		id: "a6569c34-654f-4f6c-a6bc-bb28ff44340d",
		layer_type: "cdc",
		content_key: "ghlth_crudeprev",
		title_key: "baselayer_cdc_ghlth_crudeprev",
		title: "Fair or Poor Health 18+",
		parent: "health_outcomes",
	},
];

module.exports = {
	requiredSheets,
	dictionary,
};
